### ISSUE TITLE
Better integration as a protoc plugin

### ISSUE THREAD

**Issue by bruth** [chop-dbhi/nats-rpc#2]
I am not familiar enough with protoc to create a proper plugin. Guidance or a PR are welcome!

**Comment by thetooth** [comment]
The only issue I found was the binary is not named correctly. Renaming it to `protoc-gen-nats-rpc` and having it somewhere in your PATH means you can simply use `protoc --nats-rpc_out=. service.proto`.

Also the included makefile doesn't work because the dep files are missing. Can we drop it as go get is sufficient for now?

**Comment by bruth** [comment]
Ah so it follows the same convention git uses for command naming. Good to know! I pushed a commit to rename the commands. Thanks!

The other question I had related to this was how to support custom options (flags). For example one option I would like to provide it setting a prefix to the generated NATS subjects. Right now the subjects are the [package + method name](https://github.com/chop-dbhi/nats-rpc/blob/master/example/service.pb.nats.go#L33) (which also assumes one service per package which may be a different issue).

Regarding the Makefile target, did you try running it and failed? The README instructions show to use `go get`, did that not work?

**Comment by thetooth** [comment]
See: https://godoc.org/github.com/golang/protobuf/protoc-gen-go/plugin#CodeGeneratorRequest.GetParameter

It's just a string so you can use any reasonable format. The protoc command would then become 
`protoc --nats-rpc_out=prefix=myprefix:. service.proto`

**Comment by bruth** [comment]
This is great, thank you. Previous searches throughout the docs failed to bring up this info.

Out of curiosity, have you tried out this project? If so, do you have any other general feedback?

**Comment by thetooth** [comment]
I'm playing with it atm trying to decide which one is the best fit or if I should use something other than protobuf and yeah those docs are pretty terrible.

General feel so far is pretty good, though having to pass a transport type to setup the client and server feels weird(by that I mean it would be better as an internal library), it would be nice if it just took a nats.Conn. Also the use of zap inside transport is probably unnecessary.

**Comment by bruth** [comment]
Agreed with passing in the `Transport`. It adds a bit more boilerplate than should be needed by default. An alternate constructor could be generated that takes nats.Conn.

I agree in principle it is not ideal to be forced into using a logger, but there is quite a bit of things needing to be logged since there are quite a few error cases. The choice of structured logging was preferred for our use case over strings. I realize that could still be achieved with other libraries, but we chose this.

The alternative if it poses a true issue (as suppose to opinion) is to define a Logger interface so you can plug your own implementation.

**Comment by bruth** [comment]
Fixed in 58aae76e
